const axios = require('axios');
const fs = require('fs');
const path = require('path');

async function generateTrendVisual(visualPrompt, outputFilename) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error('OPENAI_API_KEY not configured in .env file.');
  }

  console.log(`[Visual AI] Requesting DALL-E 3 portrait background for: "${visualPrompt}"`);
  
  const response = await axios.post(
    'https://api.openai.com/v1/images/generations',
    {
      model: "dall-e-3",
      prompt: visualPrompt,
      n: 1,
      size: "1024x1792", // TikTok native portrait 9:16 aspect ratio
    },
    {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      timeout: 25000
    }
  );

  const imageUrl = response.data.data[0].url;
  console.log(`[Visual AI] Image successfully generated by DALL-E 3! Downloading media from CDN...`);
  
  const imageResponse = await axios.get(imageUrl, { responseType: 'arraybuffer', timeout: 15000 });
  const cacheDir = path.resolve(__dirname, '..', 'templates', 'cache');
  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir, { recursive: true });
  
  const outputPath = path.join(cacheDir, outputFilename);
  fs.writeFileSync(outputPath, imageResponse.data);
  console.log(`[Visual AI] Dynamic custom portrait background saved at: ${outputFilename}`);
  
  return outputPath;
}

module.exports = { generateTrendVisual };
